version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "13:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: esbuild
    versions:
    - 0.10.0
    - 0.10.1
    - 0.11.0
    - 0.11.10
    - 0.11.11
    - 0.11.12
    - 0.11.13
    - 0.11.15
    - 0.11.2
    - 0.11.3
    - 0.11.5
    - 0.11.6
    - 0.11.9
    - 0.9.0
    - 0.9.1
    - 0.9.2
    - 0.9.3
    - 0.9.4
    - 0.9.6
